# Generated by Django 3.1.3 on 2020-12-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20201221_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('tel1', models.CharField(blank=True, max_length=100, null=True)),
                ('tel2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
